namespace: hello
resources:
  - ../../base
  - ingress.yaml
patches:
  - target:
      kind: Deployment
      name: hello-nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
